### PR TITLE
update to latest upstream version, fix exception with JRE >= 9

### PR DESCRIPTION
**Pull request by HiassofT**
current LE hypercon doesn't start with JRE 9 and newer. This has been fixed upstream about 2 years ago.

While at it fix the gradle build file to set source and  target compatibility versions so the generated code will be runnable on JRE >= 1.7, even if we compile with eg OpenJDK 11.

Here's a build with this PR: https://www.horus.com/~hias/tmp/libreelec/hypercon-LE.jar

### CODE REVIEW

**Comment by lrusak** [comment]
Please rebase to remove the merge commit.

Also I don’t think we need the language files as I dropped those a long time ago.

**Comment by HiassofT** [comment]
The merge commit is non-empty (needed to resolve merge conflict) so I'd rather keep it.

CZ/ES/IT language files are dropped now

**Comment by lrusak** [comment]
Please just drop the relevant language commits completely. If the merge commit contains changes then it should just be a proper commit with a relevant commit message.

**Comment by HiassofT** [comment]
redone merge, version bump split out into separate commit. the merge commit is needed to resolve the version number conflicss.

Not sure what you want with the language files, they are properly removed by a commit like you did with the german translation in abb8e840304fae5f6617c4cf27e7e2805579eb71.

**Comment by BlinkyStitt** [comment]
I just ran into this error. Is the latest commit good to merge?

**Comment by CvH** [comment]
@lrusak ping

**Comment by lrusak** [comment]
@CvH probably fine

**Pull request merged**
